"""
chat.py - The library of conversation storage class.
"""

from typing import Container


class Session(Container):
    """
    A class that represents a storage of all the messages in a conversation.
    """
    def __init__(self):
        """Initiate an empty session."""
        self.__messages: list[dict[str:str]] = []
    
    def __add__(self, messages: list[dict[str:str]]):
        self.__messages += messages
    
    def append(self, message: dict[str:str]):
        """
        Append a new message to the storage.

        Parameter
        ---------
        message: dict[str:str], a new message generated by a chatbot
        """
        self.__messages.append(message)
    
    def __delitem__(self, key: int):
        del self.__messages[key]
    
    def remove(self, index: int):
        """
        Remove the message at given index.

        Parameter
        ---------
        index: int, the index of the message to be removed.
        """
        self.__delitem__(index)
    
    def clear(self):
        """Clear the current chat."""
        self.__messages.clear()
    
    def __getitem__(self, index: int) -> dict[str:str]:
        return self.__messages[index]
    
    def __iter__(self):
        return iter(self.__messages)
    
    def __str__(self) -> str:
        return str(self.__messages)